### ISSUE TITLE
Fail to create new guard page for the stack error

### ISSUE THREAD

**Issue by ArtemisZakhary** [BenNatNB/VGMGUI#2]
Hello.

I somehow get "A new guard page for the stack cannot be created" error everytime I try to playback any VGMStream-supported file under Windows 7
![StackError](https://user-images.githubusercontent.com/44264384/78393301-2d412180-75f2-11ea-91da-37fb60ceb6bc.jpg)

**Comment by BENICHN** [comment]
Thanks for reporting this bug.

It seems to be a problem due to the calling of an external program, here it can only be VLC, unfortunately I cannot control that a priori, since I use an API package from NuGet which allows me to simply control VLC. Before deeply seeking for the solution, could you take [this build](https://github.com/BenNatNB/VGMGUI/files/4429509/VGMGUI.zip) which, among other things, has all NuGet packages updated, and try it with a fresh version of VLC downloaded by the program at first run. If it still crashes you can try to reinstall [.NET Framework 4.8 runtime](https://dotnet.microsoft.com/download), and if it doesn't work, please notify me, but I think the issue is in the API which I cannot modify, really sorry.

**Comment by BENICHN** [comment]
And if you have Visual Studio, don't hesitate to open VGMGUI in debug mode to get more informations about errors, I would like to debug this issue, but I cannot access to your system so it's impossible for me

**Comment by ArtemisZakhary** [comment]
Everything worked - the issue was in external call for VLC & outdated .Net
