### ISSUE TITLE
Can't Install Without VLC

### ISSUE THREAD

**Issue by lorenzsandi** [BenNatNB/VGMGUI#5]
I already have VLC installed on my PC but it can't be used without installing VLC itself. Won't even finish. install

**Comment by BENICHN** [comment]
vgmgui uses local vlc binaries located in a "vlc" folder. if this folder is absent from vgmgui's dir, vgmgui will download an archive on the web (http://download.videolan.org/vlc/last/win32/vlc-3.0.18-win32.zip) and extract it to the "vlc" folder. I just tested it now and vgmgui has successfully downloaded vlc.
What kind of error do you get when downloading vlc ? You can try to download it manually and to move it to vgmgui's dir (just extract "libvlc.dll", "libvlccore.dll" and "plugins" to the "vlc" folder). vgmgui will then take some time to start for the first time since it has to cache vlc plugins.

**Comment by lorenzsandi** [comment]
Did it, and it worked.
